name: Test, Build, and Deploy | Modul 01 - Lab2.2 Senior Project

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build

  deploy:
    needs: test-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/ssh-praktikan107
            
            echo "Cek folder project"
            PROJECT_DIR="${HOME}/senpro/505064/modul02/senpro-github-action"
            
            # Cloning repository jika belum ada, atau update repository jika sudah ada
            git -C "${HOME}/senpro/505064/modul02" clone https://github.com/mbudis23/senpro-github-action || \
              (cd "$PROJECT_DIR" && git restore . && git pull origin main)

            echo "Install Package and Build Project"
            cd "$PROJECT_DIR"
            npm install
            npm run build
